name: Base Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: "1.26.1"
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check Formatting
      run: |
        make checkfmt

    - name: Run Tests
      run: |
        make test
